# This patch adds pod and pod/log permissions to the existing argo-rollouts ClusterRole
# Using JSON6902 patch to add rules without replacing the entire ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-rollouts
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get

