apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  image: quay.io/kevindubois/rollouts-plugin-metric-ai-openshift # Image built from https://github.com/kdubois/rollouts-plugin-metric-ai
  version: v0.1.7
  env:
    - name: LOG_LEVEL
      value: "info"
    - name: SSL_CERT_FILE
      value: /etc/ssl/certs/openshift-ca.crt
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: argo-rollouts
          key: github_token
  plugins:
    metric:
      - name: argoproj-labs/metric-ai
        location: file:/plugins/rollouts-plugin-metric-ai/metric-ai
    trafficManagement: []
