apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  namespaceScoped: false
  env:
    - name: LOG_LEVEL
      value: "info"
    - name: SSL_CERT_FILE
      value: /etc/ssl/certs/openshift-ca.crt
  plugins:
    metric:
      - name: argoproj-labs/metric-ai
        location: file:///home/argo-rollouts/plugin-bin/rollouts-plugin-metric-ai
    trafficManagement: []
  initContainers:
    - name: copy-plugin
      image: ghcr.io/argoproj-labs/rollouts-plugin-metric-ai:latest
      command:
        - sh
        - -c
        - |
          cp /home/argo-rollouts/rollouts-plugin-metric-ai /plugin-bin/rollouts-plugin-metric-ai
          chmod +x /plugin-bin/rollouts-plugin-metric-ai
      volumeMounts:
        - name: plugin-bin
          mountPath: /plugin-bin
