apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  namespaceScoped: false
  env:
    - name: LOG_LEVEL
      value: "info"
    - name: SSL_CERT_FILE
      value: /etc/ssl/certs/openshift-ca.crt
  plugins:
    metric:
      - name: argoproj-labs/metric-ai
        location: https://github.com/kdubois/rollouts-plugin-metric-ai/releases/download/v0.1.7/rollouts-plugin-metric-ai-linux-amd64
    trafficManagement: []