apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: kubernetes-agent
          key: github_token
