apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollouts
  namespace: argo-rollouts
spec:
  version: v1.7.2
  namespaceScoped: false
  
  env:
    - name: LOG_LEVEL
      value: "info"
    - name: SSL_CERT_FILE
      value: /etc/ssl/certs/openshift-ca.crt
  
  volumes:
    - name: secrets
      secret:
        secretName: argo-rollouts
    - name: ca-certs
      configMap:
        name: cabundle
        items:
          - key: service-ca.crt
            path: openshift-ca.crt
  
  volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
      readOnly: true
    - name: ca-certs
      mountPath: /etc/ssl/certs/openshift-ca.crt
      subPath: openshift-ca.crt
      readOnly: true
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Made with Bob
