apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  image: quay.io/kevindubois/rollouts-plugin-metric-ai-openshift
  version: latest
  namespaceScoped: false
  env:
    - name: LOG_LEVEL
      value: "info"
    - name: SSL_CERT_FILE
      value: /etc/ssl/certs/openshift-ca.crt
  plugins:
    metric:
      - name: argoproj-labs/metric-ai
        location: file:///home/argo-rollouts/rollouts-plugin-metric-ai
    trafficManagement: []
