apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  namespaceScoped: false
  image: ghcr.io/argoproj-labs/rollouts-plugin-metric-ai
  version: latest
  env:
    - name: LOG_LEVEL
      value: "info"
    - name: SSL_CERT_FILE
      value: /etc/ssl/certs/openshift-ca.crt
  plugins:
    metric:
      - name: argoproj-labs/metric-ai
        # Plugin is built into the custom image at this location
        location: file:///home/argo-rollouts/rollouts-plugin-metric-ai
    trafficManagement: []
