apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  namespaceScoped: false
  env:
    - name: LOG_LEVEL
      value: "info"
    - name: SSL_CERT_FILE
      value: /etc/ssl/certs/openshift-ca.crt
