apiVersion: v1
kind: Service
metadata:
  name: quarkus-demo-canary
  namespace: quarkus-demo
  labels:
    app: quarkus-demo
    app.kubernetes.io/name: quarkus-demo
    app.kubernetes.io/part-of: quarkus-demo-app
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/component: backend
  annotations:
    app.openshift.io/vcs-uri: https://github.com/danieloh30/progressive-delivery
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: quarkus-demo
