apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ai-analysis-agent
  namespace: canary
spec:
  args:
  - name: namespace
  - name: canary-pod
  - name: stable-pod-label
    value: app=rollouts-demo,role=stable
  - name: canary-pod-label
    value: app=rollouts-demo,role=canary
  metrics:
    - name: ai-analysis
      provider:
        plugin:
          argoproj-labs/metric-ai:
            # Required: Agent URL (must be explicitly configured)
            agentUrl: http://kubernetes-agent:8080
            # Required: Pod selectors for agent to fetch logs
            stableLabel: role=stable
            canaryLabel: role=canary
            # Optional: Create GitHub issues on failures
            githubUrl: https://github.com/kdubois/progressive-delivery
            baseBranch: main
            # Optional: Additional context for AI analysis
            extraPrompt: "Ignore color changes. Consider LoadBalancerNegNotReady a temporary condition."

